[package]
name = "holiday_card"
version = "0.0.1"
edition = "2024"

[dependencies]
bevy = "*"
bevy_light_2d = { git = "https://github.com/jgayfer/bevy_light_2d.git", branch = "main" }
rand = "*"

[profile.release]
opt-level = "z"
lto = true
codegen-units = 1
